export const categories = {
  releases: 'تازه‌ها و ترندها', cinema: 'فیلم و سینمای جهان', series: 'دنیای سریال', music: 'موسیقی و هنرمندان', festivals: 'جشنواره‌ها', together: 'باهم در سرونما',
};
const rows = [
  ['imdb-trends-watch-guide', 'فیلم‌های ترند IMDb؛ چطور از موج خبرها به انتخاب خوب برسیم؟', 'releases', 'ترند IMDb', ['IMDb MovieMeter', 'فیلم ترند', 'فیلم جدید'], ['trends'], ['https://help.imdb.com/article/imdb/track-movies-tv/ratings-faq/G67Y87TFYYP6TWAV']],
  ['new-series-episode-guide', 'قسمت جدید سریال رسید؛ راهنمای پیگیری فصل‌ها بدون اسپویل', 'releases', 'قسمت جدید سریال', ['فصل و قسمت', 'دانلود سریال', 'پخش آنلاین سریال'], ['updates'], []],
  ['new-music-tags-playlists', 'آرشیو تازهٔ موسیقی سرونما؛ از تگ آهنگ تا پلی‌لیست شخصی', 'music', 'پلی لیست موسیقی', ['آهنگ جدید در آرشیو', 'تگ موسیقی', 'پلی لیست خوانندگان'], ['music-tags'], []],
  ['mobile-watch-party-guide', 'فیلم دیدن با دوستان از راه دور؛ یک شب سینمایی در موبایل', 'together', 'تماشای همزمان فیلم', ['watch together فارسی', 'تماشای همزمان در موبایل', 'اتاق فیلم'], ['The Shawshank Redemption', 'The Grand Budapest Hotel'], []],
  ['listen-together-remote-guide', 'شنیدن همزمان موسیقی؛ یک پلی‌لیست و چند دوست در یک اتاق', 'together', 'شنیدن همزمان موسیقی', ['listen together', 'پخش موسیقی با دوستان', 'اتاق موسیقی'], ['music-tags'], []],
  ['imdb-top-250-guide', '۲۵۰ فیلم برتر IMDb؛ فهرست محبوب‌ها را هوشمندانه بخوانیم', 'cinema', '250 فیلم برتر IMDb', ['امتیاز IMDb', 'بهترین فیلم ها', 'فیلم کلاسیک'], ['The Godfather', 'The Shawshank Redemption', '12 Angry Men'], ['https://help.imdb.com/article/imdb/track-movies-tv/ratings-faq/G67Y87TFYYP6TWAV']],
  ['shawshank-hope-story', 'رستگاری در شاوشنک؛ چرا قصهٔ امید دوباره تماشایی می‌شود؟', 'cinema', 'رستگاری در شاوشنک', ['The Shawshank Redemption', 'مورگان فریمن', 'فیلم امیدبخش'], ['The Shawshank Redemption', 'The Green Mile'], ['https://www.warnerbros.com/movies/shawshank-redemption']],
  ['godfather-acting-guide', 'پدرخوانده؛ قدرت، خانواده و بازیگری با کمترین کلمات', 'cinema', 'پدرخوانده', ['The Godfather', 'آل پاچینو', 'مارلون براندو'], ['The Godfather', 'The Godfather Part II'], ['https://www.paramountmovies.com/movies/the-godfather']],
  ['christopher-nolan-time-sound', 'کریستوفر نولان؛ زمان و صدا چگونه داستان را عوض می‌کنند؟', 'cinema', 'فیلم های کریستوفر نولان', ['Inception', 'Interstellar', 'موسیقی فیلم'], ['Inception', 'Interstellar', 'Dunkirk'], ['https://www.warnerbros.com/movies/inception']],
  ['breaking-bad-character-guide', 'بریکینگ بد؛ تماشای تغییر شخصیت، یک تصمیم در هر قسمت', 'series', 'بریکینگ بد', ['Breaking Bad', 'برایان کرانستون', 'سریال جنایی'], ['Breaking Bad', 'Better Call Saul'], ['https://www.sonypictures.com/tv/breakingbad']],
  ['house-hugh-laurie-guide', 'دکتر هاوس؛ طنز تلخ و بازی هیو لوری پشت یک معمای پزشکی', 'series', 'سریال House', ['هیو لوری', 'دکتر هاوس', 'سریال معمایی'], ['House'], ['https://www.nbc.com/house']],
  ['chernobyl-mini-series-guide', 'چرنوبیل و مینی‌سریال‌ها؛ روایت فشرده را چطور ببینیم؟', 'series', 'مینی سریال چرنوبیل', ['Chernobyl', 'سریال کوتاه', 'مینی سریال'], ['Chernobyl', 'The Queen\'s Gambit'], ['https://www.hbo.com/chernobyl']],
  ['cannes-palme-dor-guide', 'جشنواره کن و نخل طلا؛ پشت فرش قرمز چه اتفاقی می‌افتد؟', 'festivals', 'جشنواره کن', ['نخل طلا', 'فیلم جشنواره ای', 'Cannes'], ['Taste of Cherry', 'Parasite'], ['https://www.festival-cannes.com/en/the-festival/the-palme-d-or/']],
  ['venice-golden-lion-guide', 'جشنواره ونیز؛ شیر طلایی و مسیر کشف سینمای تازه', 'festivals', 'جشنواره ونیز', ['شیر طلایی', 'Venice Film Festival', 'سینمای مستقل'], ['Rashomon', 'Roma'], ['https://www.labiennale.org/en/history-biennale-cinema']],
  ['oscars-film-craft-guide', 'اسکار را فراتر از بهترین فیلم ببینیم؛ صدا، تدوین و بازیگری', 'festivals', 'جوایز اسکار', ['اسکار 2026', 'Academy Awards', 'موسیقی اسکار'], ['Oppenheimer', 'Parasite'], ['https://www.oscars.org/oscars/ceremonies/2026']],
  ['iranian-classic-cinema-guide', 'فیلم‌های قدیمی ایرانی؛ سفر به حافظهٔ شهری و سینمایی ما', 'cinema', 'فیلم ایرانی قدیمی', ['سینمای قبل انقلاب', 'فیلم کلاسیک ایرانی', 'آرشیو فیلم ایرانی'], ['The Cow', 'Gheysar'], ['https://www.bfi.org.uk/articles/subject/iranian-cinema']],
  ['abbas-kiarostami-cinema', 'عباس کیارستمی؛ وقتی جاده و نگاه، قصه را جلو می‌برند', 'cinema', 'فیلم های عباس کیارستمی', ['طعم گیلاس', 'کلوزآپ', 'سینمای ایران'], ['Taste of Cherry', 'Close-Up', 'Where Is the Friend\'s House?'], ['https://www.bfi.org.uk/features/where-begin-abbas-kiarostami']],
  ['asghar-farhadi-moral-drama', 'اصغر فرهادی؛ درام از جایی شروع می‌شود که قضاوت سخت است', 'cinema', 'فیلم های اصغر فرهادی', ['جدایی نادر از سیمین', 'درباره الی', 'درام ایرانی'], ['A Separation', 'About Elly', 'The Salesman'], ['https://www.oscars.org/oscars/ceremonies/2012']],
  ['korean-cinema-parasite', 'سینمای کره جنوبی؛ از انگل تا بازی‌های تازه با ژانر', 'cinema', 'سینمای کره جنوبی', ['Parasite', 'بونگ جون هو', 'فیلم کره ای'], ['Parasite', 'Memories of Murder', 'The Host'], ['https://www.bfi.org.uk/features/where-begin-with-bong-joon-ho']],
  ['japanese-cinema-kurosawa', 'سینمای ژاپن؛ شروعی با کوروساوا، حرکت و چند روایت', 'cinema', 'سینمای ژاپن', ['آکیرا کوروساوا', 'Seven Samurai', 'Rashomon'], ['Seven Samurai', 'Rashomon', 'Ikiru'], ['https://www.bfi.org.uk/features/where-begin-with-akira-kurosawa']],
  ['indian-cinema-beyond-bollywood', 'سینمای هند فراتر از بالیوود؛ زبان‌ها، ریتم‌ها و تماشاگران', 'cinema', 'سینمای هند', ['فیلم هندی', 'بالیوود', 'ساتیاجیت رای'], ['Pather Panchali', '3 Idiots', 'RRR'], ['https://www.bfi.org.uk/features/where-begin-with-satyajit-ray']],
  ['french-cinema-new-wave', 'سینمای فرانسه؛ از موج نو تا تماشای آزادانهٔ یک شهر', 'cinema', 'سینمای فرانسه', ['موج نو', 'فرانسوا تروفو', 'فیلم فرانسوی'], ['The 400 Blows', 'Breathless', 'Amélie'], ['https://www.bfi.org.uk/lists/10-great-french-new-wave-films']],
  ['italian-neorealism-guide', 'سینمای ایتالیا و نئورئالیسم؛ داستان‌های بزرگ آدم‌های معمولی', 'cinema', 'سینمای ایتالیا', ['نئورئالیسم', 'دزد دوچرخه', 'فیلم ایتالیایی'], ['Bicycle Thieves', 'Rome, Open City', 'Cinema Paradiso'], ['https://www.bfi.org.uk/film/594f7408-2fdd-55a0-a347-79370e42e0ed/bicycle-thieves']],
  ['film-score-listening-guide', 'موسیقی متن فیلم؛ یک بار تصویر را ببین، یک بار صدا را بشنو', 'music', 'موسیقی متن فیلم', ['فیلم و موسیقی', 'soundtrack', 'آهنگساز فیلم'], ['Interstellar', 'The Lord of the Rings: The Fellowship of the Ring'], ['https://www.oscars.org/oscars/ceremonies/2026']],
  ['hans-zimmer-music-guide', 'هانس زیمر؛ حجم صدا، تکرار و حس حرکت در موسیقی فیلم', 'music', 'هانس زیمر', ['Hans Zimmer', 'موسیقی Interstellar', 'موسیقی Inception'], ['Inception', 'Interstellar', 'Dune'], ['https://www.hanszimmerlive.com/']],
  ['john-williams-film-themes', 'جان ویلیامز؛ ملودی‌هایی که شخصیت فیلم می‌شوند', 'music', 'جان ویلیامز', ['John Williams', 'موسیقی جنگ ستارگان', 'موسیقی فیلم'], ['Star Wars', 'Jurassic Park', 'Schindler\'s List'], ['https://www.johnwilliams.org/reference/biography']],
  ['ebi-persian-pop-listening', 'ابی و موسیقی پاپ فارسی؛ شنیدن یک صدا در چند دوره', 'music', 'آهنگ های ابی', ['Ebi', 'پاپ فارسی', 'خواننده ایرانی'], ['music-ebi'], ['https://ebihamedi.squarespace.com/about']],
  ['googoosh-pop-memory', 'گوگوش؛ صدا، اجرا و حافظهٔ موسیقی پاپ فارسی', 'music', 'آهنگ های گوگوش', ['Googoosh', 'موسیقی قدیمی فارسی', 'پاپ ایرانی'], ['music-googoosh'], ['https://www.youtube.com/googooshvideos']],
  ['focus-chill-music-playlist', 'پلی‌لیست تمرکز؛ چطور موسیقی را همراه کار کنیم؟', 'music', 'موسیقی برای تمرکز', ['Chill', 'موسیقی بی کلام', 'پلی لیست آرام'], ['music-tags'], []],
  ['personal-music-playlist-guide', 'پلی‌لیست خودت را بساز؛ از یک آهنگ محبوب تا یک مسیر شنیدنی', 'music', 'ساخت پلی لیست موسیقی', ['دسته بندی آهنگ', 'پلی لیست شخصی', 'شنیدن همزمان'], ['music-tags'], []],
];

export const firstMonth = rows.map(([slug, title, category, primaryKeyword, keywords, selectors, sources], i) => ({
  slug, title, category, categoryLabel: categories[category], primaryKeyword,
  keywords: [primaryKeyword, ...keywords, 'سرونما'], selectors,
  sources: [{ title: 'آرشیو و امکانات سرونما', url: 'https://sarvnema.ir' }, ...sources.map(url => ({ title: new URL(url).hostname.replace(/^www\./, '') + ' · منبع مرجع', url }))],
  manuscript: `${String(i + 1).padStart(2, '0')}-${slug}.md`,
  relatedSlugs: rows.filter(row => row[2] === category && row[0] !== slug).slice(0, 4).map(row => row[0]),
  image: `/media/magazine/${['music', 'festivals', 'together'].includes(category) ? category : 'editorial-cinema-music'}-branded.webp`,
  imageAlt: category === 'music' ? 'تصویرسازی اختصاصی صفحهٔ موسیقی و هدفون در اتاق شنیدن' : category === 'festivals' ? 'تصویرسازی فرش قرمز در برابر یک سالن سینمای خیالی' : category === 'together' ? 'تصویرسازی یک قرار فیلم با دوستان و ارتباط تصویری' : 'تصویرسازی سینمایی پروژکتور فیلم و اتاق موسیقی برای مجله سرونما',
}));
