export const BODYBUILDING_CELEBRITIES = [
  {
    name: "امین آذرنشین",
    title: "مربی و تولیدکننده محتوای بدنسازی",
    instagram: "aminazarneshin_coach",
    url: "https://www.instagram.com/aminazarneshin_coach/",
    note: "آموزش بدنسازی، نکات تمرین و محتوای پرمخاطب فارسی برای ورزشکارهای باشگاهی.",
  },
  {
    name: "جاویدنام مسعود ذات‌پرور",
    title: "قهرمان پرورش‌اندام و مربی بدنسازی",
    instagram: "mahdi_zatparvar",
    url: "https://fa.wikipedia.org/wiki/مسعود_ذات‌پرور",
    note: "قهرمان اهل رشت و دانش‌آموخته فیزیولوژی ورزشی؛ این ورودی به یاد جاویدنام مسعود ذات‌پرور در رمق نمایش داده می‌شود.",
  },
  {
    name: "بهروز تابانی",
    title: "IFBB Pro Open Bodybuilder",
    instagram: "behrouz_tabani",
    url: "https://www.instagram.com/behrouz_tabani/",
    note: "بدنساز حرفه‌ای ایرانی و از چهره‌های مهم صحنه‌های بین‌المللی اوپن.",
  },
  {
    name: "هانی رامبد",
    title: "Olympia-winning coach",
    instagram: "hanyrambod",
    url: "https://www.instagram.com/hanyrambod/",
    note: "مربی ایرانی‌تبار قهرمان‌های المپیا و خالق سیستم FST-7.",
  },
  {
    name: "مهسا اکبری‌مهر",
    title: "IFBB Bikini Pro",
    instagram: "mahsa_ifbbpro",
    url: "https://www.instagram.com/mahsa_ifbbpro/",
    note: "از چهره‌های ایرانی فیتنس و بیکینی پرو؛ تمرکز روی کاهش چربی و فیتنس بانوان.",
  },
  {
    name: "سپیده ابشاری",
    title: "Persian Fit Model Pro",
    instagram: "sepidehabshari",
    url: "https://www.instagram.com/sepidehabshari/",
    note: "فیت مدل و مربی سبک زندگی/پوزینگ با هویت ایرانی و محتوای تمرینی بانوان.",
  },
  {
    name: "رویا کریمی",
    title: "IFBB World Champion Coach",
    instagram: "roya.ifbb.pro.coach",
    url: "https://www.instagram.com/roya.ifbb.pro.coach/",
    note: "مربی فیتنس و سبک زندگی؛ مناسب برای معرفی مسیر بانوان در فیتنس رقابتی.",
  },
  {
    name: "وحید بدپی",
    title: "Classic Physique IFBB Pro",
    instagram: "vahidbadpei_ifbbpro",
    url: "https://www.instagram.com/vahidbadpei_ifbbpro/",
    note: "چهره ایرانی کلاسیک فیزیک و مسابقات حرفه‌ای.",
  },
  {
    name: "یزدان رحمت‌آبادی",
    title: "IFBB Pro",
    instagram: "ifbbpro_yazdan",
    url: "https://www.instagram.com/ifbbpro_yazdan/",
    note: "بدنساز حرفه‌ای ایرانی با محتوای تمرینی و آمادگی مسابقه.",
  },
  {
    name: "دامون اشتری",
    title: "متخصص تغذیه ورزشی",
    instagram: "damoon_ashtary",
    url: "https://www.instagram.com/damoon_ashtary/",
    note: "تغذیه ورزشی، فیتنس و آموزش سبک زندگی سالم برای مخاطب فارسی‌زبان.",
  },
  {
    name: "ستار میرلوحی",
    title: "مربی خصوصی و آنلاین",
    instagram: "sattar.fit",
    url: "https://www.instagram.com/sattar.fit/",
    note: "محتوای تمرینی و برنامه‌محور برای مخاطب عمومی فیتنس.",
  },
  {
    name: "دکتر امید صالحیان",
    title: "تغذیه ورزشی و تناسب اندام",
    instagram: "dr.salehian",
    url: "https://www.instagram.com/dr.salehian/",
    note: "آموزش تغذیه، تناسب اندام و نگاه علمی‌تر به برنامه ورزشی.",
  },
  {
    name: "دکتر کرمانی",
    title: "رژیم و مدیریت وزن",
    instagram: "drkermany",
    url: "https://www.instagram.com/drkermany/",
    note: "برند شناخته‌شده ایرانی در رژیم آنلاین، کاهش وزن و آموزش تغذیه.",
  },
  {
    name: "رضا شورمیج",
    title: "مربی پیشرفته بدنسازی IFBB",
    instagram: "reza_shoormeij",
    url: "https://www.instagram.com/reza_shoormeij/",
    note: "مربی بدنسازی و فیتنس با تمرکز روی آموزش، کشتی و آماده‌سازی بدنی.",
  },
  {
    name: "فدراسیون بدنسازی ایران",
    title: "صفحه رسمی/خبری بدنسازی ایران",
    instagram: "iranbbf.en",
    url: "https://www.instagram.com/iranbbf.en/",
    note: "برای دنبال کردن خبرهای رسمی‌تر بدنسازی و پرورش اندام ایران.",
  },
  {
    name: "Iran Muscle",
    title: "رسانه بدنسازی ایران",
    instagram: "iranmuscle",
    url: "https://www.instagram.com/iranmuscle/",
    note: "رسانه پرمخاطب فارسی برای اخبار، مسابقات و چهره‌های بدنسازی.",
  },
  {
    name: "Chris Bumstead",
    title: "Classic Physique Olympia",
    instagram: "cbum",
    url: "https://www.instagram.com/cbum/",
    note: "یکی از محبوب‌ترین چهره‌های کلاسیک فیزیک و الهام‌بخش میلیون‌ها ورزشکار.",
  },
  {
    name: "Derek Lunsford",
    title: "Mr. Olympia",
    instagram: "dereklunsford_",
    url: "https://www.instagram.com/dereklunsford_/",
    note: "قهرمان اوپن مستر المپیا و از نام‌های اصلی بدنسازی حرفه‌ای مدرن.",
  },
  {
    name: "Ronnie Coleman",
    title: "8x Mr. Olympia",
    instagram: "ronniecoleman8",
    url: "https://www.instagram.com/ronniecoleman8/",
    note: "اسطوره بدنسازی و یکی از پرافتخارترین قهرمان‌های تاریخ مستر المپیا.",
  },
  {
    name: "Jay Cutler",
    title: "4x Mr. Olympia",
    instagram: "jaycutler",
    url: "https://www.instagram.com/jaycutler/",
    note: "قهرمان افسانه‌ای و چهره مهم فرهنگ تمرین و بدنسازی.",
  },
  {
    name: "Phil Heath",
    title: "7x Mr. Olympia",
    instagram: "philheath",
    url: "https://www.instagram.com/philheath/",
    note: "از موفق‌ترین بدنسازهای مدرن با محتوای انگیزشی و آموزشی.",
  },
  {
    name: "Kai Greene",
    title: "Bodybuilding icon",
    instagram: "kaigreene",
    url: "https://www.instagram.com/kaigreene/",
    note: "چهره خلاق و محبوب بدنسازی با سبک هنری و انگیزشی خاص.",
  },
  {
    name: "Flex Lewis",
    title: "7x 212 Olympia",
    instagram: "flex_lewis",
    url: "https://www.instagram.com/flex_lewis/",
    note: "قهرمان دسته ۲۱۲ و صاحب برند Dragon's Lair.",
  },
  {
    name: "Arnold Schwarzenegger",
    title: "Bodybuilding legend",
    instagram: "schwarzenegger",
    url: "https://www.instagram.com/schwarzenegger/",
    note: "اسطوره بدنسازی، سینما و فرهنگ فیتنس جهان.",
  },
  {
    name: "Dana Linn Bailey",
    title: "Physique champion",
    instagram: "danalinnbailey",
    url: "https://www.instagram.com/danalinnbailey/",
    note: "از چهره‌های محبوب فیزیک بانوان و تمرین قدرتی.",
  },
  {
    name: "Andrea Shaw",
    title: "Ms. Olympia",
    instagram: "mzprettymuscle",
    url: "https://www.instagram.com/mzprettymuscle/",
    note: "قهرمان بدنسازی بانوان و یکی از نام‌های اصلی صحنه Ms. Olympia.",
  },
  {
    name: "Cydney Gillon",
    title: "Figure Olympia",
    instagram: "vytamin_c",
    url: "https://www.instagram.com/vytamin_c/",
    note: "قهرمان فیگور المپیا و الگوی حرفه‌ای برای تمرین بانوان.",
  },
  {
    name: "Ashley Kaltwasser",
    title: "Bikini Olympia",
    instagram: "ashleykfit",
    url: "https://www.instagram.com/ashleykfit/",
    note: "از موفق‌ترین ورزشکاران بیکینی با محتوای آماده‌سازی و سبک زندگی.",
  },
  {
    name: "Angelica Teixeira",
    title: "Bikini Olympia champion",
    instagram: "angelicaht",
    url: "https://www.instagram.com/angelicaht/",
    note: "چهره مطرح بیکینی، پوزینگ و آماده‌سازی مسابقه.",
  },
  {
    name: "Erin Stern",
    title: "Figure Olympia champion",
    instagram: "2x_ms_olympia",
    url: "https://www.instagram.com/2x_ms_olympia/",
    note: "قهرمان فیگور و مربی با محتوای آموزشی کاربردی.",
  },
  {
    name: "Michelle Lewin",
    title: "Fitness model",
    instagram: "michelle_lewin",
    url: "https://www.instagram.com/michelle_lewin/",
    note: "فیتنس مدل شناخته‌شده با محتوای تمرین و سبک زندگی.",
  },
  {
    name: "Jeff Nippard",
    title: "Science-based lifting",
    instagram: "jeffnippard",
    url: "https://www.instagram.com/jeffnippard/",
    note: "محتوای علمی تمرین، هایپرتروفی و برنامه‌نویسی برای ورزشکاران.",
  },
  {
    name: "Layne Norton",
    title: "Coach and researcher",
    instagram: "biolayne",
    url: "https://www.instagram.com/biolayne/",
    note: "آموزش علمی تغذیه، تمرین و نقد ادعاهای رایج فیتنس.",
  },
  {
    name: "Bret Contreras",
    title: "Glute training specialist",
    instagram: "bretcontreras1",
    url: "https://www.instagram.com/bretcontreras1/",
    note: "شناخته‌شده برای آموزش تمرین باسن، هیپ‌تراست و برنامه‌نویسی پایین‌تنه.",
  },
  {
    name: "Sohee Lee",
    title: "Coach and educator",
    instagram: "soheefit",
    url: "https://www.instagram.com/soheefit/",
    note: "محتوای آموزشی درباره تغذیه، رفتار غذایی و تمرین پایدار.",
  },
  {
    name: "Meg Gallagher",
    title: "Strength coach",
    instagram: "megsquats",
    url: "https://www.instagram.com/megsquats/",
    note: "تمرین قدرتی، پاورلیفتینگ و فرهنگ مثبت تمرین برای بانوان.",
  },
  {
    name: "Noel Deyzel",
    title: "Fitness creator",
    instagram: "noeldeyzel_bodybuilder",
    url: "https://www.instagram.com/noeldeyzel_bodybuilder/",
    note: "محتوای انگیزشی، تمرین و سبک زندگی بدنسازی برای مخاطب عمومی.",
  },
] as const;
