"use client";

// Branded, printable diet-plan export. We render a clean HTML document in a new
// window and trigger the browser's print dialog ("Save as PDF") — this renders
// Persian/RTL and shaping perfectly (unlike jsPDF) and needs no fonts bundled.

import type { DietPlan, PlanMeal, Supplement } from "./foods";
import type { DietProfile, MacroTargets } from "./nutrition";

const FA_DIGITS = "۰۱۲۳۴۵۶۷۸۹";
const fa = (v: string | number) => String(v).replace(/\d/g, (d) => FA_DIGITS[+d]);

export function downloadDietPdf(opts: {
  lang: "fa" | "en";
  profile: DietProfile;
  targets: MacroTargets;
  plan: DietPlan;
  supplements: Supplement[];
  extras: { fiber: number; waterL: number };
  goalLabel: string;
  mealName: (name: string) => string;
}) {
  const { lang, profile, targets, plan, supplements, extras, goalLabel, mealName } = opts;
  const rtl = lang === "fa";
  const num = (v: string | number) => (rtl ? fa(v) : String(v));
  const L = rtl
    ? {
        brand: "رمق",
        tagline: "برنامه‌ی تغذیه‌ی اختصاصی",
        target: "هدف روزانه",
        kcal: "کیلوکالری",
        protein: "پروتئین",
        carbs: "کربوهیدرات",
        fat: "چربی",
        fiber: "فیبر",
        water: "آب",
        profile: "مشخصات",
        meals: "وعده‌های غذایی",
        day: "روز",
        supps: "مکمل‌های پیشنهادی",
        dose: "دوز",
        timing: "زمان",
        made: "تولیدشده توسط اپلیکیشن رمق",
        goal: "هدف",
        gramsShort: "گرم",
      }
    : {
        brand: "Ramagh",
        tagline: "Personalized nutrition plan",
        target: "Daily target",
        kcal: "kcal",
        protein: "Protein",
        carbs: "Carbs",
        fat: "Fat",
        fiber: "Fiber",
        water: "Water",
        profile: "Profile",
        meals: "Meals",
        day: "Day",
        supps: "Recommended supplements",
        dose: "Dose",
        timing: "Timing",
        made: "Generated by the Ramagh app",
        goal: "Goal",
        gramsShort: "g",
      };

  const esc = (s: string) =>
    s.replace(/[&<>"]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[c]!));

  const dayHtml = (meals: PlanMeal[], idx: number) => `
    <section class="day">
      ${plan.days.length > 1 ? `<h3 class="dayh">${L.day} ${num(idx + 1)}</h3>` : ""}
      ${meals
        .map(
          (m) => `
        <div class="meal">
          <div class="meal-head">
            <span class="meal-name">${esc(mealName(m.name))}</span>
            <span class="meal-kcal">${num(m.kcal)} ${L.kcal}</span>
          </div>
          <ul class="items">
            ${m.items
              .map(
                (it) =>
                  `<li><span>${esc(rtl ? it.nameFa : it.name)} <em>${esc(it.label)}</em></span><span class="ikcal">${num(it.kcal)}</span></li>`
              )
              .join("")}
          </ul>
          <div class="macros"><b class="p">P ${num(m.protein)}</b> <b class="c">C ${num(m.carbs)}</b> <b class="f">F ${num(m.fat)}</b></div>
        </div>`
        )
        .join("")}
    </section>`;

  const html = `<!doctype html><html lang="${lang}" dir="${rtl ? "rtl" : "ltr"}"><head>
<meta charset="utf-8"><title>${L.brand} — ${L.tagline}</title>
<style>
  * { box-sizing: border-box; }
  body { font-family: ${rtl ? "'Tahoma','Segoe UI',sans-serif" : "'Segoe UI',Arial,sans-serif"}; color:#1a2230; margin:0; padding:28px 30px; background:#fff; }
  .top { display:flex; align-items:center; justify-content:space-between; border-bottom:3px solid #7bd93a; padding-bottom:14px; }
  .logo { display:flex; align-items:center; gap:10px; }
  .mark { width:42px; height:42px; border-radius:12px; background:#7bd93a; color:#0b1418; display:flex; align-items:center; justify-content:center; font-weight:900; font-size:22px; }
  .brand { font-size:26px; font-weight:900; }
  .tagline { color:#5c6b7a; font-size:13px; margin-top:2px; }
  .meta { text-align:${rtl ? "left" : "right"}; font-size:12px; color:#5c6b7a; }
  .target { margin-top:18px; background:linear-gradient(135deg,#7bd93a,#5bb62f); color:#0b1418; border-radius:16px; padding:16px 18px; }
  .target .big { font-size:34px; font-weight:900; }
  .macros-row { display:flex; gap:10px; margin-top:10px; }
  .macros-row div { flex:1; background:rgba(11,20,24,.12); border-radius:10px; padding:8px; text-align:center; }
  .macros-row .v { font-size:18px; font-weight:900; }
  .macros-row .k { font-size:11px; opacity:.75; }
  .sub { display:flex; gap:16px; margin-top:8px; font-size:12px; font-weight:700; opacity:.85; }
  h2 { font-size:16px; margin:22px 0 10px; color:#2b7a0f; border-bottom:1px solid #e6ebef; padding-bottom:6px; }
  .dayh { font-size:14px; color:#2b7a0f; margin:14px 0 8px; font-weight:800; }
  .meal { border:1px solid #e6ebef; border-radius:12px; padding:10px 12px; margin-bottom:8px; break-inside:avoid; }
  .meal-head { display:flex; justify-content:space-between; font-weight:800; }
  .meal-kcal { color:#2b7a0f; }
  .items { list-style:none; margin:8px 0 0; padding:0; }
  .items li { display:flex; justify-content:space-between; font-size:13px; padding:2px 0; color:#38424f; }
  .items em { color:#8894a0; font-style:normal; font-size:11px; }
  .ikcal { color:#8894a0; font-size:12px; }
  .macros { margin-top:8px; padding-top:6px; border-top:1px dashed #e6ebef; font-size:12px; }
  .macros .p{color:#c0392b} .macros .c{color:#2b7a0f} .macros .f{color:#b7791f}
  .supp { display:flex; justify-content:space-between; align-items:flex-start; border:1px solid #e6ebef; border-radius:12px; padding:10px 12px; margin-bottom:6px; break-inside:avoid; }
  .supp .n { font-weight:800; }
  .supp .why { font-size:12px; color:#5c6b7a; margin-top:2px; }
  .supp .r { text-align:${rtl ? "left" : "right"}; font-size:12px; white-space:nowrap; }
  .tier { display:inline-block; font-size:10px; font-weight:900; border-radius:6px; padding:1px 5px; background:#eaf7dd; color:#2b7a0f; margin-${rtl ? "right" : "left"}:6px; }
  footer { margin-top:22px; border-top:1px solid #e6ebef; padding-top:10px; font-size:11px; color:#8894a0; text-align:center; }
  @media print { body { padding:14px; } .no-print { display:none; } }
</style></head><body>
  <div class="top">
    <div class="logo"><div class="mark">${rtl ? "ر" : "R"}</div><div><div class="brand">${L.brand}</div><div class="tagline">${L.tagline}</div></div></div>
    <div class="meta">${L.goal}: ${esc(goalLabel)}<br>${esc(new Date().toLocaleDateString(rtl ? "fa-IR" : "en-US", { year: "numeric", month: "long", day: "numeric" }))}</div>
  </div>

  <div class="target">
    <div style="font-size:12px;font-weight:700;opacity:.75">${L.target}</div>
    <div class="big">${num(targets.kcal)} <span style="font-size:15px">${L.kcal}</span></div>
    <div class="macros-row">
      <div><div class="v">${num(targets.protein)}${L.gramsShort}</div><div class="k">${L.protein}</div></div>
      <div><div class="v">${num(targets.carbs)}${L.gramsShort}</div><div class="k">${L.carbs}</div></div>
      <div><div class="v">${num(targets.fat)}${L.gramsShort}</div><div class="k">${L.fat}</div></div>
    </div>
    <div class="sub"><span>${L.fiber}: ${num(extras.fiber)}${L.gramsShort}</span><span>${L.water}: ${num(extras.waterL)} ${rtl ? "لیتر" : "L"}</span></div>
  </div>

  <h2>${L.meals}</h2>
  ${plan.days.map((d, i) => dayHtml(d, i)).join("")}

  ${
    supplements.length
      ? `<h2>${L.supps}</h2>` +
        supplements
          .map(
            (s) => `<div class="supp"><div><div class="n">${esc(rtl ? s.nameFa : s.name)}<span class="tier">${s.tier}</span></div><div class="why">${esc(rtl ? s.whyFa : s.why)}</div></div><div class="r">${L.dose}: ${esc(num(s.dose))}<br>${L.timing}: ${esc(rtl ? s.timingFa : s.timing)}</div></div>`
          )
          .join("")
      : ""
  }

  <footer>${L.made} · ramagh</footer>
  <script>window.onload=function(){setTimeout(function(){window.print();},350);};</script>
</body></html>`;

  const w = window.open("", "_blank");
  if (!w) return;
  w.document.open();
  w.document.write(html);
  w.document.close();
}
