// Converts the MuscleWiki body SVGs (extracted from the rendered site into
// mw-svgs.json by a one-time Playwright run) into lib/bodysvg.ts.
// Male figures come from the homepage; female from an ?model=f page.

import { readFileSync, writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const SRC = resolve(
  process.env.LOCALAPPDATA ?? "",
  "Temp/claude/C--Users-yadro/76a40e8e-5a74-488d-ad33-d88ebbc6b4bf/scratchpad/mw-svgs.json"
);

const data = JSON.parse(readFileSync(SRC, "utf8"));
const keys = Object.keys(data);
const maleKey = keys.find((k) => !k.includes("model=f"));
const femaleKey = keys.find((k) => k.includes("model=f"));

function clean(svg) {
  return (
    svg
      // neutral root: our CSS controls sizing; keep the viewBox
      .replace(/<svg[^>]*?>/, (m) => {
        const vb = m.match(/viewBox="[^"]+"/)?.[0] ?? 'viewBox="0 0 660.46 1206.46"';
        return `<svg ${vb} fill="none" xmlns="http://www.w3.org/2000/svg">`;
      })
      // ids must not collide when four figures are on one page → strip joint-group
      // duplicate ids on decorative ellipses, keep group ids (we scope by container).
      .replace(/\sid="hover[^"]*"/g, "")
      // drop tailwind classes from the source site (we style via our own CSS)
      .replace(/\sclass="bodymap[^"]*"/g, ' data-muscle="1"')
  );
}

/** Front figure lists abdominals/biceps/chest…; back lists glutes/lats/… */
function isFront(svg) {
  return svg.includes('id="chest"') || svg.includes('id="abdominals"');
}

function pair(key) {
  const svgs = data[key].map(clean);
  const front = svgs.find(isFront);
  const back = svgs.find((s) => !isFront(s));
  if (!front || !back) throw new Error("could not split front/back for " + key);
  return { front, back };
}

const m = pair(maleKey);
const f = pair(femaleKey);

const out = `// AUTO-GENERATED by scripts/build-bodysvg.mjs — do not edit by hand.
// Original artwork © MuscleWiki (musclewiki.com); used for personal, non-commercial use.

export const BODY_SVGS = {
  male: { front: ${JSON.stringify(m.front)}, back: ${JSON.stringify(m.back)} },
  female: { front: ${JSON.stringify(f.front)}, back: ${JSON.stringify(f.back)} },
} as const;
`;

writeFileSync(resolve(__dirname, "..", "lib", "bodysvg.ts"), out, "utf8");
console.log(
  "written lib/bodysvg.ts:",
  Object.entries({ mF: m.front.length, mB: m.back.length, fF: f.front.length, fB: f.back.length })
    .map(([k, v]) => `${k}=${(v / 1024).toFixed(1)}kb`)
    .join(" ")
);
